data_preprocessing:
  min_overview_words: 6
  max_overview_words: 169
  top_cast: 5
  top_keywords: 10

paths:
  tmdb_download: "asaniczka/tmdb-movies-dataset-2023-930k-movies"
  lb_download: "https://huggingface.co/datasets/pkchwy/letterboxd-all-movie-data/resolve/main/full_dump.jsonl"
  tmdb_raw: "data/raw/TMDB_movie_dataset_v11.csv"
  lb_raw: "data/raw/full_dump.jsonl"
  film_data: "data/prep/film_data.csv"
  faiss_index: "data/prep/faiss_index.ivf"
  faiss_metadata: "data/prep/faiss_metadata.pkl"

models:
  embedding_model: "Snowflake/snowflake-arctic-embed-m"
  
  data_preprocessing:
  min_overview_words: 6
  max_overview_words: 169
  top_cast: 5
  top_keywords: 10

paths:
  tmdb_download: "asaniczka/tmdb-movies-dataset-2023-930k-movies"
  lb_download: "https://huggingface.co/datasets/pkchwy/letterboxd-all-movie-data/resolve/main/full_dump.jsonl"
  tmdb_raw: "data/raw/TMDB_movie_dataset_v11.csv"
  lb_raw: "data/raw/full_dump.jsonl"
  film_data: "data/prep/film_data.csv"
  faiss_index: "data/prep/faiss_index.ivf"
  faiss_metadata: "data/prep/faiss_metadata.pkl"

models:
  embedding_model: "Snowflake/snowflake-arctic-embed-m"

  # LLM settings
  llm_repo: "TheBloke/Llama-2-13B-Chat-GGUF"
  llm_filename: "llama-2-13b-chat.Q4_K_M.gguf"
  chat_format: "llama-2"

llm_params:
  n_ctx: 1025
  n_threads: 8
  temperature: 0.7
  max_tokens: 512