data_preprocessing:
  min_overview_words: 6
  max_overview_words: 169
  top_cast: 5
  top_keywords: 10

paths:
  tmdb_download: "asaniczka/tmdb-movies-dataset-2023-930k-movies"
  lb_download: "https://huggingface.co/datasets/pkchwy/letterboxd-all-movie-data/resolve/main/full_dump.jsonl"
  tmdb_raw: "data/raw/TMDB_movie_dataset_v11.csv"
  lb_raw: "data/raw/full_dump.jsonl"
  film_data: "data/prep/film_data.csv"
  faiss_index: "data/prep/faiss_index.ivf"
  faiss_metadata: "data/prep/faiss_metadata.pkl"
  embeddings: "data/prep/embeddings_full.npy"

models:
  embedding_model: "Snowflake/snowflake-arctic-embed-m"
  llm_repo: "TheBloke/Mistral-7B-Instruct-v0.1-GGUF"
  llm_filename: "mistral-7b-instruct-v0.1.Q4_K_M.gguf"
  chat_format: "mistral-instruct"

llm_params:
  n_ctx: 2048
  n_threads: 8
  temperature: 0.7
  max_tokens: 512